version: '3.8'
services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - MYSQL_HOST=${MYSQLHOST}
      - MYSQL_USER=${MYSQLUSER}
      - MYSQL_PASSWORD=${MYSQLPASSWORD}
      - MYSQL_DATABASE=${MYSQLDATABASE}
      - MYSQL_PORT=${MYSQLPORT}